Update action.yaml

diff --git a/.github/workflows/action.yaml b/.github/workflows/action.yaml
--- a/.github/workflows/action.yaml
+++ b/.github/workflows/action.yaml
@@ -11,5 +11,18 @@ jobs:
     steps:
       - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
       - name: execute test case
+        env:
+          BODY: ${{ github.event.pull_request.body }}
         run: |
-          echo "executing test code goes here..."
+          UNCHECKED="\[ \] integration test"
+          MARKED="\[x\] integration test"
+           if echo ${BODY,,} | grep -q "$MARKED"; then
+            echo "Checkbox is checked"
+            exit 0
+          elif echo ${BODY,,} | grep -q "$UNCHECKED"; then
+            echo "Checkbox is not checked"
+            exit 1
+          else
+            echo "Checkbox not found in pull request description"
+            exit 1
+          fi
